title: FieldTrip Bugzilla
email: r.oostenveld@donders.ru.nl
description: ""
baseurl: ""
url: "https://bugzilla.fieldtriptoolbox.org"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

#remote_theme: pages-themes/architect
#remote_theme: pages-themes/cayman
#remote_theme: pages-themes/hacker
#remote_theme: pages-themes/leap-day
#remote_theme: pages-themes/midnight
#remote_theme: pages-themes/minimal
#remote_theme: pages-themes/modernist
#remote_theme: pages-themes/slate
#remote_theme: pages-themes/time-machine
#remote_theme: benbalter/retlab
#remote_theme: cyevgeniy/jekyll-true-minimal
remote_theme: riggraz/no-style-please

#theme: dinky
#theme: merlot
#theme: minima
#theme: tactile

theme_config:
  show_description: true

collections:
  pages:
    output: false
    permalink: /:path
  posts:
    output: false
    permalink: /:path
    
exclude:
  - README.md
  - Gemfile*
  - _code/*
